name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
    - Ascaniolamp

body:
    - type: markdown
      attributes:
          value: |
              When reporting bugs, please follow the guidelines in this template to help fix the problem quickly and precisely.
              - Write a descriptive issue title above.
              - Always open *one* issue for *one* bug. If you want to report several bugs, make sure to create one new issue for each of them.
              - Search open and closed issues to ensure it hasn't been reported already. If you don't find a relevant match or if you're unsure, don't hesitate to **open a new issue**, others will handle it from there if it's a duplicate.
              - If you use a custom build, please test if your issue is reproducible in official builds too.

    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false

    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: "A bug happened!"
      validations:
          required: true

    - type: dropdown
      id: browsers
      attributes:
          label: What submodule does the problem happen on?
          multiple: true
          options:
              - Hyprland
              - GTK or Qt
              - SDDM
              - Rofi
              - Vesktop
              - Spotify
              - Albert
              - Others

    - type: input
      attributes:
          label: System information
          description: |
              - Specify the OS version and relevant hardware information.
              - **Bug reports not including the required information may be closed at the maintainers' discretion.** If in doubt, always include all the requested information; it's better to include too much information than not enough information.
          placeholder: OS - VERSION - GPU - CPU
      validations:
          required: true

    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](../CODE_OF_CONDUCT.md).
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
